const headers={'Accept':'application/vnd.github+json','User-Agent':'FRP-Programmers-Dashboard','X-GitHub-Api-Version':'2022-11-28'};
async function github<T>(path:string){const res=await fetch(`https://api.github.com/repos/${path}`,{headers});if(!res.ok)throw new Error(res.status===403||res.status===429?'GitHub’s public request limit was reached. Please try again later.':res.status===404?'Repository or file not found. Check that the repository is public.':'GitHub is temporarily unavailable.');return res.json() as Promise<T>}
export async function GET(req:Request){try{const q=new URL(req.url).searchParams,repo=q.get('repo')||'',path=q.get('path')||'',ref=q.get('ref')||'';if(!/^[\w.-]+\/[\w.-]+$/.test(repo)||path.length>1000||path.split('/').includes('..')||ref&&!/^[a-f0-9]{40}$/.test(ref))return Response.json({error:'Enter a public GitHub repository as owner/repository.'},{status:400});
 let sha=ref;if(!sha){const info=await github<{default_branch:string}>(repo);const commit=await github<{sha:string}>(`${repo}/commits/${encodeURIComponent(info.default_branch)}`);sha=commit.sha;}
 const item=await github<{type:string;encoding:string;size:number;content:string}|{name:string;path:string;type:string}[]>(`${repo}/contents/${path.split('/').map(encodeURIComponent).join('/')}?ref=${sha}`);
 if(Array.isArray(item))return Response.json({ref:sha,path,entries:item.map(x=>({name:x.name,path:x.path,type:x.type})).sort((a,b)=>a.type===b.type?a.name.localeCompare(b.name):a.type==='dir'?-1:1)});
 if(item.type!=='file'||item.encoding!=='base64'||item.size>500000)return Response.json({error:'This preview supports text files up to 500 KB. Open this file on GitHub to view it.'},{status:422});
 const bytes=Uint8Array.from(atob(item.content.replace(/\s/g,'')),c=>c.charCodeAt(0));const content=new TextDecoder().decode(bytes);if(content.includes('\u0000'))return Response.json({error:'Binary files cannot be previewed. Open this file on GitHub.'},{status:422});
 return Response.json({ref:sha,path,content},{headers:{'Cache-Control':'public, max-age=30'}});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'Could not load GitHub.'},{status:502})}}
